# Generated by Django 5.1.3 on 2024-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Kurs nomi')),
                ('info', models.TextField(verbose_name='Kurs haqida malumot')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='qoshilgan Vaqti')),
                ('update_at', models.TimeField(auto_now=True, verbose_name='Yangilangal vaqti')),
                ('cours_logo', models.ImageField(upload_to='curslogos/', verbose_name='curs logosi')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, unique=True, verbose_name='Dars nomi')),
                ('description', models.TextField(verbose_name='dars haqida')),
                ('will_be', models.DateTimeField(verbose_name='Qchon boladi')),
                ('photo', models.ImageField(upload_to='lessonphotos/', verbose_name='dars rasmi')),
            ],
        ),
    ]
